platform :ios, '18.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  abort "#{generated} must exist." unless File.exist?(generated)
  File.foreach(generated) do |line|
    return $1.strip if line =~ /FLUTTER_ROOT\=(.*)/
  end
  abort "FLUTTER_ROOT not found in Generated.xcconfig"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Make ALL pods accept Xcode 16 simulator
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

      # Fix LevelDB / gRPC / Abseil module verifier failures
      config.build_settings['ENABLE_MODULE_VERIFIER'] = 'NO'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end

    flutter_additional_ios_build_settings(target)
  end
end
